### ISSUE TITLE
DMRG-CASPT2

### ISSUE THREAD

**Issue by huuco** [SebWouters/CheMPS2#23]
Hi Sebastian,

Is it possible to use DMRG-CASPT2 without Psi4? 
I am using Molcas and would like to compare DMRG-CASPT2 with full CASPT2 of Molcas, using the same active space. I can generate the FCIDUMP file with Molcas.

Best regards

**Comment by SebWouters** [comment]
@huuco 

Yes. You should just pass a pointer to a convergence scheme instead of a NULL pointer on the lines 67-68 of https://github.com/SebWouters/CheMPS2/blob/master/tests/test14.cpp.in. An example of such a convergence scheme can be found in https://github.com/SebWouters/CheMPS2/blob/master/tests/test9.cpp.in.

If you don't know anything about DMRG yet, please catch up on that first. You need multiple consecutive instructions in the convergence scheme instead of the single one in test9 for larger systems.

That all being said: I don't support CASPT2 yet until there's a chemps2 v1.7 release. Please take a look at the comments in https://github.com/psi4/psi4/issues/266#issuecomment-186113504.
